---
- name: Stop and disable services
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: stopped
    enabled: no
    scope: user
  loop:
    - pod-redis
  ignore_errors: true

- name: Remove pod and containers
  containers.podman.podman_pod:
    name: redis
    state: absent
  ignore_errors: true

- name: Remove systemd services
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/systemd/user/{{ item }}"
    state: absent
  loop:
    - pod-redis.service
    - container-redis-server.service
    - container-redis-gui.service

- name: Remove Quadlet files
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/containers/systemd/{{ item }}"
    state: absent
  loop:
    - redis.pod
    - redis-server.container
    - redis-gui.container

- name: Reload systemd user daemon
  ansible.builtin.systemd:
    daemon_reload: yes
    scope: user

- name: Remove data directory
  ansible.builtin.file:
    path: "{{ redis_data_dir }}"
    state: absent
  when: redis_delete_data | bool