---
#
# .......................................................................................
- name: reload systemd user daemon
  ansible.builtin.systemd:
    daemon_reload: yes
    scope: user

# .......................................................................................
- name: Enable and start pod with systemd
  ansible.builtin.systemd:
    name: "{{ redis_service_name }}"
    state: started
    enabled: yes
    scope: user
