---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
    ignore-errors: true

driver:
  name: podman
  options:
    managed: true
    platform_name: ${MOLECULE_PLATFORM_NAME:-all}

# Testing containers for solti-containers collection
# These images have systemd, SSH, and necessary tooling
platforms:
  - name: "uut-deb12"
    image: "ghcr.io/jackaltx/testing-containers/debian-ssh:12"
    command: "/sbin/init"
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    ssh_host: "127.0.0.1"
    ssh_port: 2223
    ssh_user: "jackaltx"
    connection: ssh

  - name: "uut-rocky9"
    image: "ghcr.io/jackaltx/testing-containers/rocky-ssh:9"
    command: "/sbin/init"
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    ssh_host: "127.0.0.1"
    ssh_port: 2222
    ssh_user: "jackaltx"
    connection: ssh

  - name: "uut-ct2"
    image: "ghcr.io/jackaltx/testing-containers/ubuntu-ssh:24"
    command: "/sbin/init"
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    ssh_host: "127.0.0.1"
    ssh_port: 2224
    ssh_user: "jackaltx"
    connection: ssh

provisioner:
  name: ansible
  env:
    ANSIBLE_FORCE_COLOR: "1"
  log: true
  config_options:
    defaults:
      interpreter_python: auto_silent
      host_key_checking: false
      remote_tmp: /tmp/ansible-tmp
      local_tmp: /tmp/ansible-tmp
      ansible_managed: "Ansible managed"
  playbooks:
    prepare: "../shared/podman/prepare.yml"
    converge: "converge.yml"
    verify: "../shared/verify/main.yml"
  inventory:
    host_vars:
      all:
        selected_platform: "${MOLECULE_PLATFORM_NAME}"
    group_vars:
      all:
        project_root: ${MOLECULE_PROJECT_DIRECTORY}
        report_root: ${MOLECULE_PROJECT_DIRECTORY}/verify_output

        # Default testing role - can be overridden
        test_role: "${MOLECULE_TEST_ROLE:-redis}"

scenario:
  name: github
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - cleanup
    - destroy

verifier:
  name: ansible
