---
- name: Stop and disable services
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: stopped
    enabled: no
    scope: user
  loop:
    - mattermost-pod
  ignore_errors: true

- name: Remove pod and containers
  containers.podman.podman_pod:
    name: mattermost-pod
    state: absent
  ignore_errors: true

- name: Remove systemd services
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/systemd/user/{{ item }}"
    state: absent
  loop:
    - mattermost-pod.service

- name: Remove data directory
  ansible.builtin.file:
    path: "{{ mattermost_data_dir }}"
    state: absent
  when: mattermost_delete_data | bool