---
- name: Stop and disable services
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: stopped
    enabled: no
    scope: user
  loop:
    - pod-mattermost
  ignore_errors: true

- name: Remove pod and containers
  containers.podman.podman_pod:
    name: pod-mattermost
    state: absent
  ignore_errors: true

- name: Remove systemd services
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/systemd/user/{{ item }}"
    state: absent
  loop:
    - container-mattermost-db.service
    - container-mattermost-svc.service
    - pod-mattermost.service

# ...........................................
- name: Reload systemd user daemon
  ansible.builtin.systemd:
    daemon_reload: yes
    scope: user

# ...........................................
- name: Remove data directory
  ansible.builtin.file:
    path: "{{ mattermost_data_dir }}"
    state: absent
  when: mattermost_delete_data | bool
