---
#
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#
- name: Set service name based on deployment type
  set_fact:
    mattermost_service_name: "pod-mattermost"
    mattermost_pod_key: "mattermost"
  when: not mattermost_use_quadlet | bool

# .................................................................
- name: Stop and disable services
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: stopped
    enabled: no
    scope: user
  loop:
    - "{{ mattermost_service_name }}"
  ignore_errors: true

# .................................................................
# These are only present when generated
#
- name: Remove systemd services
  when: not mattermost_use_quadlet | bool
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/systemd/user/{{ item }}"
    state: absent
  loop:
    - container-mattermost-db.service
    - container-mattermost-svc.service
    - pod-mattermost.service

# ...........................................
- name: Remove Quadlet files
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/containers/systemd/{{ item }}"
    state: absent
  loop:
    - mattermost-db.container
    - mattermost-svc.container
    - mattermost.pod

# ...........................................
- name: reload systemd user daemon
  ansible.builtin.systemd:
    daemon_reload: yes
    scope: user

# .................................................................
- name: Remove all traces
  become: true
  when: mattermost_state == 'absent' and mattermost_purge | default(false)
  block:
    - name: Remove configuration
      file:
        path: "{{ mattermost_data_dir }}"
        state: absent
    - name: Remove systemd files
      file:
        path: "{{ item }}"
        state: absent
      with_fileglob:
        - "~/.config/systemd/user/*mattermost*"
