---
#
# ..........................................................
- name: Ensure pod is removed if it exists
  containers.podman.podman_pod:
    name: mattermost-pod
    state: absent
  ignore_errors: true

# ..........................................................
- name: Create Mattermost pod
  containers.podman.podman_pod:
    name: mattermost-pod
    ports:
      - "{{ mattermost_port }}:8065"

# ..........................................................
- name: Deploy PostgreSQL container
  containers.podman.podman_container:
    name: mattermost-db
    pod: mattermost-pod
    image: "{{ mattermost_postgres_image }}"
    state: started
    volume:
      - "{{ mattermost_data_dir }}/postgres:/var/lib/postgresql/data:Z"
    env:
      POSTGRES_USER: "{{ mattermost_db_user }}"
      POSTGRES_PASSWORD: "{{ mattermost_postgres_password }}"
      POSTGRES_DB: "{{ mattermost_db_name }}"
    restart_policy: always

# ..........................................................
- name: Wait for PostgreSQL to be ready
  ansible.builtin.wait_for:
    host: localhost
    port: 5432
    timeout: 30
  register: pg_wait_result
  ignore_errors: true

# ..........................................................
- name: Deploy Mattermost container
  containers.podman.podman_container:
    name: mattermost
    pod: mattermost-pod
    image: "{{ mattermost_image }}"
    state: started
    volume:
      - "{{ mattermost_data_dir }}/config:/mattermost/config:Z"
      - "{{ mattermost_data_dir }}/data:/mattermost/data:Z"
      - "{{ mattermost_data_dir }}/logs:/mattermost/logs:Z"
      - "{{ mattermost_data_dir }}/plugins:/mattermost/plugins:Z"
      - "{{ mattermost_data_dir }}/client/plugins:/mattermost/client/plugins:Z"
    restart_policy: always
    depends_on:
      - mattermost-db
