---
#
# ..........................................................
- name: Ensure pod is removed if it exists
  containers.podman.podman_pod:
    name: mattermost
    state: absent
  ignore_errors: true

# ..........................................................
- name: Create Mattermost pod
  containers.podman.podman_pod:
    name: mattermost
    ports:
      - "{{ mattermost_port }}:8065"
  register: pod_result

# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
- name: Verify pod status
  ansible.builtin.command: podman pod inspect mattermost
  register: pod_status
  changed_when: false

# ..........................................................
- name: Deploy PostgreSQL container
  containers.podman.podman_container:
    name: mattermost-db
    pod: mattermost
    image: "{{ mattermost_postgres_image }}"
    state: started
    volume:
      - "{{ mattermost_data_dir }}/postgres:/var/lib/postgresql/data:Z"
    env:
      POSTGRES_USER: "{{ mattermost_db_user }}"
      POSTGRES_PASSWORD: "{{ mattermost_postgres_password }}"
      POSTGRES_DB: "{{ mattermost_db_name }}"
    restart_policy: always

# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
- name: Verify PostgreSQL container status
  ansible.builtin.command: podman inspect mattermost-db
  register: postgres_status
  changed_when: false

# ..........................................................
- name: Wait for PostgreSQL to initialize
  ansible.builtin.pause:
    seconds: 10
  when:
    - not ansible_check_mode

# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
- name: Verify pod still exists
  ansible.builtin.command: podman pod inspect mattermost
  register: pod_status_before_mattermost
  changed_when: false

# ..........................................................
- name: Deploy Mattermost container
  containers.podman.podman_container:
    name: mattermost-svc
    pod: mattermost
    image: "{{ mattermost_image }}"
    state: started
    volume:
      - "{{ mattermost_data_dir }}/config:/mattermost/config:Z"
      - "{{ mattermost_data_dir }}/data:/mattermost/data:Z"
      - "{{ mattermost_data_dir }}/logs:/mattermost/logs:Z"
      - "{{ mattermost_data_dir }}/plugins:/mattermost/plugins:Z"
      - "{{ mattermost_data_dir }}/client/plugins:/mattermost/client/plugins:Z"
    restart_policy: always
#
#  note: claude insists on adding depend_on:, but that is not valid
#
