---
# Create TLS directory structure if TLS is enabled
- name: Create TLS directory
  ansible.builtin.file:
    path: "{{ mattermost_data_dir }}/config/tls"
    state: directory
    mode: "0750"
  when: mattermost_enable_tls | bool

# ...................................................
- name: Create Mattermost config
  ansible.builtin.template:
    src: config.json.j2
    dest: "{{ mattermost_data_dir }}/config/config.json"
    mode: "0644"
