---
- name: Create systemd user directory
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/systemd/user"
    state: directory
    mode: '0750'

- name: Create systemd service for pod
  ansible.builtin.template:
    src: mattermost-pod.service.j2
    dest: "{{ ansible_user_dir }}/.config/systemd/user/mattermost-pod.service"
    mode: '0644'

- name: Reload systemd user daemon
  ansible.builtin.systemd:
    daemon_reload: yes
    scope: user

- name: Enable and start pod with systemd
  ansible.builtin.systemd:
    name: mattermost-pod
    state: started
    enabled: yes
    scope: user

- name: Enable lingering for user
  ansible.builtin.command: loginctl enable-linger {{ ansible_user_id }}
  become: true
  changed_when: false