---
#
# .......................................................................................
- name: Create systemd user directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/systemd/user"
    state: directory
    mode: "0750"

# .......................................................................................
- name: Generate pod service file
  ansible.builtin.command:
    cmd: podman generate systemd --name mattermost --files --new
    chdir: "{{ ansible_env.HOME }}/.config/systemd/user"
  register: generate_result

- name: Debug generate result
  ansible.builtin.debug:
    var: generate_result

# .......................................................................................
- name: Reload systemd user daemon
  ansible.builtin.systemd:
    daemon_reload: yes
    scope: user

# .......................................................................................
- name: Enable and start pod with systemd
  ansible.builtin.systemd:
    name: pod-mattermost
    state: started
    enabled: yes
    scope: user
# .......................................................................................
# - name: Enable and start container services
#   ansible.builtin.systemd:
#     name: "{{ item }}"
#     state: started
#     enabled: yes
#     scope: user
#   loop:
#     - container-mattermost-db
#     - container-mattermost
