---
galaxy_info:
  role_name: hashivault
  namespace: jackaltx
  author: jackaltx
  description: Deploy HashiCorp Vault secrets management using Podman containers
  license: MIT
  min_ansible_version: "2.9"

  platforms:
    - name: EL
      versions:
        - "9"
    - name: Debian
      versions:
        - bookworm
    - name: Ubuntu
      versions:
        - jammy

  galaxy_tags:
    - vault
    - secrets
    - hashicorp
    - podman
    - containers

dependencies: []
