---
- name: Validate state parameter
  ansible.builtin.fail:
    msg: "obsidian_state must be one of: prepare, present, absent"
  when: obsidian_state not in ['prepare', 'present', 'absent']

# Get real user info (immune to become)
# =======================================================================
# MATRIX EVENT
# =======================================================================
- name: send matrix event
  ansible.builtin.include_tasks:
    file: "../_base/tasks/matrix_event.yml"
