---
#
# Installation state
redis_state: present
redis_force_reload: false

# No TLS, cause this is for fast local use only
#

# Container settings
redis_image: "docker.io/library/redis:7.2-alpine"
redis_commander_image: "docker.io/rediscommander/redis-commander:latest"

# Directory settings
redis_data_dir: "{{ ansible_user_dir }}/redis-data"

# Redis settings
redis_port: 6379
redis_gui_port: 8081
redis_password: "{{ lookup('env', 'REDIS_PASSWORD') | default('changeme') }}"
redis_maxmemory: "256mb"
redis_maxmemory_policy: "allkeys-lru"

# Security settings
redis_enable_tls: false
redis_tls_cert_file: ""
redis_tls_key_file: ""
redis_tls_auth_clients: "no"

# GUI settings
redis_enable_gui: true

# Cleanup settings
redis_delete_data: false

# ....................................................................................
# quadlets
#        "redis-infra",
#        "redis-svc",
#        "redis-gui"
#        "redis-pod"
#
redis_service_name: "redis-pod"
redis_pod_key: "redis.pod"

# ----------------------------------------------
# Common variables needed by base role
#

service_name: "redis-pod"
service_pod_key: "redis.pod"
service_quadlets:
  - "redis-svc",
  - "redis-gui"
  - "redis-pod"  

service_data_dir: "{{ redis_data_dir }}"
service_config_dir: "{{ redis_data_dir }}/config"
service_image: "{{ redis_image }}"

service_dirs:
  - { path: "", mode: "0750" }
  - { path: "config", mode: "0755" }
  - { path: "data", mode: "0750" }

service_ports:
  - "127.0.0.1:{{ redis_port }}:6379"
  - "127.0.0.1:{{ redis_gui_port }}:8081"

service_volumes:
  - "{{ service_data_dir }}/config:/usr/local/etc/redis:Z"
  - "{{ service_data_dir }}/data:/data:Z"

service_command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
