---
# Installation state
redis_state: present
redis_force_reload: false

# Container settings
redis_image: "docker.io/library/redis:7.2-alpine"
redis_commander_image: "docker.io/rediscommander/redis-commander:latest"

# Directory settings
redis_data_dir: "{{ ansible_user_dir }}/redis-data"

# Redis settings
redis_port: 6379
redis_gui_port: 8081
redis_password: "changeme"
redis_maxmemory: "256mb"
redis_maxmemory_policy: "allkeys-lru"

# Security settings
redis_enable_tls: false
redis_tls_cert_file: ""
redis_tls_key_file: ""
redis_tls_auth_clients: "no"

# GUI settings
redis_enable_gui: true

# Cleanup settings
redis_delete_data: false