---
# This task generates self-signed certificates for Wazuh components using more basic/compatible options

- name: Check if certificates already exist
  ansible.builtin.stat:
    path: "{{ wazuh_data_dir }}/certs/root-ca.pem"
  register: cert_check

- name: Generate certificates
  when: not cert_check.stat.exists
  become: true
  block:
    # Create temporary directory for certificate generation
    - name: Create temporary directory
      ansible.builtin.tempfile:
        state: directory
        suffix: wazuh_certs
      register: cert_temp_dir

    # Generate CA Key
    - name: Generate CA private key
      community.crypto.openssl_privatekey:
        path: "{{ cert_temp_dir.path }}/root-ca.key"
        type: RSA
        size: 4096

    # Generate CA Certificate using minimal parameters
    - name: Generate CA certificate
      ansible.builtin.command: >
        openssl req -x509 -new -nodes
        -key {{ cert_temp_dir.path }}/root-ca.key
        -sha256 -days {{ wazuh_ca_cert_days }}
        -out {{ cert_temp_dir.path }}/root-ca.pem
        -subj "/CN=Wazuh CA/O=Wazuh Inc./OU=Wazuh Security/C=US"
        -extensions v3_ca
        -config <(echo "[req]"; 
                 echo "distinguished_name=req";
                 echo "[v3_ca]";
                 echo "basicConstraints=critical,CA:TRUE";
                 echo "keyUsage=keyCertSign,cRLSign")
      args:
        executable: /bin/bash
      changed_when: true

    # Generate component certificates using a loop
    - name: Generate certificates for Wazuh components
      include_tasks: generate_component_cert_simple.yml
      loop:
        - name: "wazuh-manager"
          cn: "wazuh-manager.{{ service_dns_search }}"
          san_dns:
            - "wazuh-manager"
            - "wazuh-manager.{{ service_dns_search }}"
            - "localhost"
          san_ip:
            - "127.0.0.1"
        - name: "wazuh-indexer"
          cn: "wazuh-indexer.{{ service_dns_search }}"
          san_dns:
            - "wazuh-indexer"
            - "wazuh-indexer.{{ service_dns_search }}"
            - "localhost"
          san_ip:
            - "127.0.0.1"
        - name: "wazuh-dashboard"
          cn: "wazuh-dashboard.{{ service_dns_search }}"
          san_dns:
            - "wazuh-dashboard"
            - "wazuh-dashboard.{{ service_dns_search }}"
            - "localhost"
          san_ip:
            - "127.0.0.1"

    # Copy certificates to their final location
    - name: Copy certificates to their final location
      ansible.builtin.copy:
        src: "{{ cert_temp_dir.path }}/"
        dest: "{{ wazuh_data_dir }}/certs/"
        remote_src: true
        owner: "{{ dir_info.stat.uid }}"
        group: "{{ dir_info.stat.gid }}"
        mode: "0640"

    # Clean up
    - name: Remove temporary certificate directory
      ansible.builtin.file:
        path: "{{ cert_temp_dir.path }}"
        state: absent
