---
# ............................................................
- name: Verify prerequisites
  assert:
    that:
      - wazuh_data_dir is defined
    fail_msg: "Required variables not properly configured"

# ............................................................
- name: Base prepare
  ansible.builtin.include_tasks:
    file: ../_base/tasks/prepare.yml
