---
# .......................................................................
- name: Verify prerequisite variables
  assert:
    that:
      - wazuh_admin_password != "changeme"
      - wazuh_api_password != "changeme"
      - wazuh_data_dir is defined
      - wazuh_api_port is defined
    fail_msg: "Required variables not properly configured"

# .......................................................................
- name: Become root and apply configuration
  become: true
  block:
    # ...................................................
    # Configure system settings for Elasticsearch
    - name: Configure system settings for Elasticsearch
      block:
        - name: Configure max map count (required for Elasticsearch)
          ansible.builtin.sysctl:
            name: vm.max_map_count
            value: "262144"
            sysctl_set: yes
            state: present
            reload: yes

        - name: Configure memory overcommit
          ansible.builtin.sysctl:
            name: vm.overcommit_memory
            value: "1"
            sysctl_set: yes
            state: present
            reload: yes

        - name: Disable swapping
          ansible.builtin.sysctl:
            name: vm.swappiness
            value: "1"
            sysctl_set: yes
            state: present
            reload: yes

    # ...................................................
    # there are three containers, each may have own uid:gid

    # Manager

    - name: Get manager config directory ownership
      ansible.builtin.stat:
        path: "{{ wazuh_data_dir }}/config/manager"
      register: dir_info

    - name: Template manager config
      ansible.builtin.template:
        src: ossec.conf.xml.j2
        dest: "{{ wazuh_data_dir }}/config/manager/ossec.conf"
        mode: "0644"
        owner: "{{ dir_info.stat.uid }}"
        group: "{{ dir_info.stat.gid }}"
      notify: restart wazuh manager

    - name: Template manager ruleset
      ansible.builtin.template:
        src: local_rules.xml.j2
        dest: "{{ wazuh_data_dir }}/config/manager/local_rules.xml"
        mode: "0644"
        owner: "{{ dir_info.stat.uid }}"
        group: "{{ dir_info.stat.gid }}"
      notify: restart wazuh manager

    - name: Ensure data directories exist with proper permissions
      ansible.builtin.file:
        path: "{{ wazuh_data_dir }}/data/manager"
        state: directory
        owner: "{{ dir_info.stat.uid }}"
        group: "{{ dir_info.stat.gid }}"
        mode: "0755"

    # Indexer

    - name: Get manager config directory ownership
      ansible.builtin.stat:
        path: "{{ wazuh_data_dir }}/config/indexer"
      register: dir_info

    - name: Template indexer config
      ansible.builtin.template:
        src: elasticsearch.yml.j2
        dest: "{{ wazuh_data_dir }}/config/indexer/elasticsearch.yml"
        mode: "0644"
        owner: "{{ dir_info.stat.uid }}"
        group: "{{ dir_info.stat.gid }}"
      notify: restart wazuh indexer

    - name: Ensure data directories exist with proper permissions
      ansible.builtin.file:
        path: "{{ wazuh_data_dir }}/data/indexer"
        state: directory
        owner: "{{ dir_info.stat.uid }}"
        group: "{{ dir_info.stat.gid }}"
        mode: "0755"

    # Dashboard

    - name: Get manager dashboard directory ownership
      ansible.builtin.stat:
        path: "{{ wazuh_data_dir }}/config/dashboard"
      register: dir_info

    - name: Template dashboard config
      ansible.builtin.template:
        src: opensearch_dashboards.yml.j2
        dest: "{{ wazuh_data_dir }}/config/dashboard/opensearch_dashboards.yml"
        mode: "0644"
        owner: "{{ dir_info.stat.uid }}"
        group: "{{ dir_info.stat.gid }}"
      notify: restart wazuh dashboard

    - name: Get manager data/dashboard-config directory ownership
      ansible.builtin.stat:
        path: "{{ wazuh_data_dir }}/data/dashboard/wazuh"
      register: dir_info

    - name: Template dashboard wazuh config
      ansible.builtin.template:
        src: wazuh_dashboard.yml.j2
        dest: "{{ wazuh_data_dir }}/data/dashboard/wazuh/config/wazuh.yml"
        mode: "0644"
        owner: "{{ dir_info.stat.uid }}"
        group: "{{ dir_info.stat.gid }}"
      notify: restart wazuh dashboard

    # Create data directories with proper permissions
    # - name: Ensure data directories exist with proper permissions
    #   ansible.builtin.file:
    #     path: "{{ wazuh_data_dir }}/data/dashboard"
    #     state: directory
    #     owner: "{{ dir_info.stat.uid }}"
    #     group: "{{ dir_info.stat.gid }}"
    #     mode: "0755"

    # ...................................................
    - name: Configure SELinux for data directories
      when: ansible_os_family == "RedHat" and ansible_selinux.status == "enabled"
      block:
        - name: Set SELinux context for data directories
          ansible.builtin.sefcontext:
            target: "{{ wazuh_data_dir }}(/.*)?"
            setype: container_file_t
            state: present

        - name: Apply SELinux context
          ansible.builtin.command: restorecon -R -v "{{ wazuh_data_dir }}"
          register: restorecon_result
          changed_when: restorecon_result.rc == 0
