---
# .............................................................................
- name: Ensure required directories exist
  ansible.builtin.file:
    path: "/etc/containers/systemd/env"
    state: directory
    mode: "0750"

# .............................................................................
- name: Create environment file for Wazuh
  ansible.builtin.template:
    src: wazuh.env.j2
    dest: "/etc/containers/systemd/env/wazuh.env"
    mode: "0600"

# .............................................................................
- name: Create Wazuh pod Quadlet
  containers.podman.podman_pod:
    name: wazuh
    state: quadlet
    dns: "{{ service_dns_servers }}"
    dns_search: "{{ service_dns_search }}"
    network: "{{ service_network }}"
    quadlet_dir: "/etc/containers/systemd"
    ports:
      - "0.0.0.0:{{ wazuh_api_port }}:{{ wazuh_api_port }}" # SMELL!!!!  55000
      - "0.0.0.0:{{ wazuh_manager_port }}:{{ wazuh_manager_port }}" # Wazuh manager 1514
      - "0.0.0.0:{{ wazuh_registration_port }}:{{ wazuh_registration_port }}" # Wazuh manager 1515
      - "127.0.0.1:{{ wazuh_dashboard_port }}:{{ wazuh_dashboard_port }}" # Wazuh dashboard 8082
      - "127.0.0.1:{{ wazuh_indexer_port}}:{{ wazuh_indexer_port }}" # Wazuh indexer 9201 ???
    quadlet_options:
      # - "Label=traefik.enable=true"
      # - "Label=traefik.http.routers.wazuh.rule=Host(`wazuh.{{ domain }}`)"
      # - "Label=traefik.http.routers.wazuh.entrypoints=websecure"
      # - "Label=traefik.http.routers.wazuh.service=wazuh"
      # - "Label=traefik.http.services.wazuh.loadbalancer.server.port={{ wazuh_dashboard_port }}"
      # - "Label=traefik.http.routers.wazuh.middlewares=secHeaders@file"
      - |
        [Service]
        Restart=always
      - |
        [Install]
        WantedBy=multi-user.target  # Changed from default.target

# .............................................................................
- name: Create Wazuh containers with volumes for certificates
  containers.podman.podman_container:
    name: "{{ item.name }}"
    pod: wazuh.pod
    image: "{{ item.image }}"
    state: quadlet
    quadlet_dir: "/etc/containers/systemd"
    volume: "{{ item.volumes }}"
    env: "{{ item.env }}"
    quadlet_options: "{{ item.options }}"
  loop:
    # .............
    - name: "wazuh-indexer"
      image: "{{ wazuh_indexer_image }}"
      volumes:
        #
        #  The configuration file must be exactly places and use U to set correct uid/gid
        #
        # - "{{ wazuh_data_dir }}/config/indexer:/usr/share/wazuh-indexer/config:Z,U"
        - "{{ wazuh_data_dir }}/config/indexer/elasticsearch.yml:/usr/share/wazuh-indexer/opensearch.yml:Z,U"
        - "{{ wazuh_data_dir }}/data/indexer:/var/lib/wazuh-indexer:Z,U"
        #
        #  Certs are not being processed now... monkey patch worked, dir patch no
        #
        # - "{{ wazuh_data_dir }}/certs:/usr/share/wazuh-indexer/certs:z,U,ro"
        - "{{ wazuh_data_dir }}/certs/indexer/wazuh-indexer.pem:/usr/share/wazuh-indexer/certs/wazuh-indexer.pem:Z,U,ro"
        - "{{ wazuh_data_dir }}/certs/indexer/wazuh-indexer.key:/usr/share/wazuh-indexer/certs/wazuh-indexer.key:Z,U,ro"
        - "{{ wazuh_data_dir }}/certs/indexer/root-ca.pem:/usr/share/wazuh-indexer/certs/root-ca.pem:Z,U,ro"
        #
        # Logs directory (test only??)
        #
        - "{{ wazuh_data_dir }}/logs/indexer:/var/log/wazuh-indexer:Z,U"
      env:
        OPENSEARCH_JAVA_OPTS: "-Xms{{ wazuh_indexer_memory }} -Xmx{{ wazuh_indexer_memory }}  -Djava.security.manager=allow"
      options:
        # Add ulimit settings
        - "Ulimit=memlock=-1:-1"
        - "Ulimit=nofile=65535:65535"
        - |
          [Unit]
          Description=Wazuh Indexer Container
          After=network-online.target
        - |
          [Service]
          Restart=always
          TimeoutStartSec=300
          TimeoutStopSec=70
        - |
          [Install]
          WantedBy=multi-user.target

    # .............
    - name: "wazuh-manager"
      image: "{{ wazuh_manager_image }}"
      volumes:
        - "{{ wazuh_data_dir }}/data/manager:/var/ossec/data:Z,U"
        - "{{ wazuh_data_dir }}/filebeat/etc:/etc/filebeat:Z,U"
        - "{{ wazuh_data_dir }}/filebeat/var:/var/lib/filebeat:Z,U"
        #
        - "{{ wazuh_data_dir }}/config/manager:/var/ossec/configuration:Z,U"
        - "{{ wazuh_data_dir }}/config/manager/ossec.conf:/var/ossec/etc/ossec.conf:Z,U"
        #
        - "{{ wazuh_data_dir }}/certs/manager/wazuh-manager.pem:/etc/ssl/filebeat.pem:Z,U,ro"
        - "{{ wazuh_data_dir }}/certs/manager/wazuh-manager.key:/etc/ssl/filebeat.key:Z,U,ro"
        - "{{ wazuh_data_dir }}/certs/manager/root-ca.pem:/etc/ssl/root-ca.pem:Z,U,ro"
        #
        # Logs directory (test only??)
        #
        - "{{ wazuh_data_dir }}/logs/manager:/var/ossec/logs:Z,U"
        #
      env:
        INDEXER_URL: "https://wazuh-indexer:{{ wazuh_indexer_port }}"
        INDEXER_USERNAME: "admin"
        INDEXER_PASSWORD: "{{ wazuh_admin_password }}"
        FILEBEAT_SSL_VERIFICATION_MODE: "full"
      options:
        - |
          [Unit]
          Description=Wazuh Manager Container
          After=wazuh-indexer.service
        - |
          [Service]
          Restart=always
          TimeoutStartSec=300
          TimeoutStopSec=70
        - |
          [Install]
          WantedBy=multi-user.target

    # .............
    - name: "wazuh-dashboard"
      image: "{{ wazuh_dashboard_image }}"
      volumes:
        # - "{{ wazuh_data_dir }}/data/dashboard:/usr/share/wazuh-dashboard/data:Z,U"
        #
        #  Do a file patch ONLY for config and certs
        #
        - "{{ wazuh_data_dir }}/config/dashboard/opensearch_dashboards.yml:/usr/share/wazuh-dashboard/config/opensearch_dashboards.yml:Z,U"
        - "{{ wazuh_data_dir }}/config/dashboard/wazuh.yml:/usr/share/wazuh-dashboard/data/wazuh/config/wazuh.yml:Z,U"
        #
        - "{{ wazuh_data_dir }}/certs/dashboard/wazuh-dashboard.pem:/usr/share/wazuh-dashboard/certs/wazuh-dashboard.pem:Z,U,ro"
        - "{{ wazuh_data_dir }}/certs/dashboard/wazuh-dashboard.key:/usr/share/wazuh-dashboard/certs/wazuh-dashboard.key:Z,U,ro"
        - "{{ wazuh_data_dir }}/certs/dashboard/root-ca.pem:/usr/share/wazuh-dashboard/certs/root-ca.pem:Z,U,ro"
        #
      env:
        OPENSEARCH_JAVA_OPTS: "-Xms{{ wazuh_dashboard_memory }} -Xmx{{ wazuh_dashboard_memory }}"
        INDEXER_USERNAME: "admin"
        INDEXER_PASSWORD: "{{ wazuh_admin_password }}"
        API_USERNAME: "{{ wazuh_api_user }}"
        API_PASSWORD: "{{ wazuh_api_password }}"
        # Add these for better connectivity
        WAZUH_API_URL: "https://wazuh-manager"
        ELASTICSEARCH_URL: "https://wazuh-indexer:{{ wazuh_indexer_port }}"
        NODE_TLS_REJECT_UNAUTHORIZED: "0" # For testing - remove in production
      options:
        - "SecurityLabelDisable=true"
        - |
          [Unit]
          Description=Wazuh Dashboard Container
          After=wazuh-manager.service
        - |
          [Service]
          Restart=always
          TimeoutStartSec=300
          TimeoutStopSec=70
        - |
          [Install]
          WantedBy=multi-user.target

# .......................................................................................
- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: yes

# .......................................................................................
- name: "Enable and start pod with systemd: {{ service_properties.name }}"
  ansible.builtin.systemd:
    name: "{{ service_properties.name }}"
    state: started
    enabled: yes
