---
# .............................................................................
- name: Ensure required directories exist
  ansible.builtin.file:
    path: "/etc/containers/systemd"
    state: directory
    mode: "0750"

# .............................................................................
- name: Create environment file for Wazuh
  ansible.builtin.template:
    src: wazuh.env.j2
    dest: "/etc/containers/systemd/env/wazuh.env"
    mode: "0600"

# .............................................................................
- name: Create Wazuh pod Quadlet
  containers.podman.podman_pod:
    name: wazuh
    state: quadlet
    dns: "{{ service_dns_servers }}"
    dns_search: "{{ service_dns_search }}"
    network: "{{ service_network }}"
    quadlet_dir: "/etc/containers/systemd"
    ports:
      - "0.0.0.0:{{ wazuh_api_port }}:55000" # Now binding to all interfaces
      - "0.0.0.0:{{ wazuh_manager_port }}:1514"
      - "0.0.0.0:{{ wazuh_registration_port }}:1515"
      - "0.0.0.0:{{ wazuh_dashboard_port }}:443" # Wazuh dashboard
    quadlet_options:
      - |
        [Service]
        Restart=always
      - |
        [Install]
        WantedBy=multi-user.target  # Changed from default.target

# .............................................................................
- name: Create Wazuh containers
  containers.podman.podman_container:
    name: "{{ item.name }}"
    pod: wazuh.pod
    image: "{{ item.image }}"
    state: quadlet
    quadlet_dir: "/etc/containers/systemd"
    volume: "{{ item.volumes }}"
    env: "{{ item.env }}"
    quadlet_options: "{{ item.options }}"
  loop:
    - name: "wazuh-indexer"
      image: "{{ wazuh_indexer_image }}"
      volumes:
        - "{{ wazuh_data_dir }}/config/indexer:/usr/share/wazuh-indexer/config:Z"
        - "{{ wazuh_data_dir }}/data/indexer:/var/lib/wazuh-indexer:Z"
        - "{{ wazuh_data_dir }}/certs:/etc/ssl/wazuh:Z,ro"
      env:
        OPENSEARCH_JAVA_OPTS: "-Xms{{ wazuh_indexer_memory }} -Xmx{{ wazuh_indexer_memory }}"
      options:
        - |
          [Unit]
          Description=Wazuh Indexer Container
          After=network-online.target
        - |
          [Service]
          Restart=always
          TimeoutStartSec=300
          TimeoutStopSec=70
        - |
          [Install]
          WantedBy=multi-user.target

    - name: "wazuh-manager"
      image: "{{ wazuh_manager_image }}"
      volumes:
        - "{{ wazuh_data_dir }}/config/manager:/var/ossec/etc:Z"
        - "{{ wazuh_data_dir }}/data/manager:/var/ossec/data:Z"
        - "{{ wazuh_data_dir }}/certs:/etc/ssl/wazuh:Z,ro"
      env:
        INDEXER_URL: "https://wazuh-indexer:9200"
        INDEXER_USERNAME: "admin"
        INDEXER_PASSWORD: "{{ wazuh_admin_password }}"
        FILEBEAT_SSL_VERIFICATION_MODE: "full"
      options:
        - |
          [Unit]
          Description=Wazuh Manager Container
          After=wazuh-indexer.service
        - |
          [Service]
          Restart=always
          TimeoutStartSec=300
          TimeoutStopSec=70
        - |
          [Install]
          WantedBy=multi-user.target

    - name: "wazuh-dashboard"
      image: "{{ wazuh_dashboard_image }}"
      volumes:
        - "{{ wazuh_data_dir }}/config/dashboard:/usr/share/wazuh-dashboard/config:Z"
        - "{{ wazuh_data_dir }}/data/dashboard:/usr/share/wazuh-dashboard/data:Z"
        - "{{ wazuh_data_dir }}/data/dashboard/wazuh/config/wazuh.yml:/usr/share/wazuh-dashboard/data/wazuh/config/wazuh.yml:Z"
        - "{{ wazuh_data_dir }}/certs:/etc/ssl/wazuh:Z,ro"
      env:
        OPENSEARCH_JAVA_OPTS: "-Xms{{ wazuh_dashboard_memory }} -Xmx{{ wazuh_dashboard_memory }}"
        INDEXER_USERNAME: "admin"
        INDEXER_PASSWORD: "{{ wazuh_admin_password }}"
        API_USERNAME: "{{ wazuh_api_user }}"
        API_PASSWORD: "{{ wazuh_api_password }}"
      options:
        - "SecurityLabelDisable=true"
        - |
          [Unit]
          Description=Wazuh Dashboard Container
          After=wazuh-manager.service
        - |
          [Service]
          Restart=always
          TimeoutStartSec=300
          TimeoutStopSec=70
        - |
          [Install]
          WantedBy=multi-user.target

# .......................................................................................
- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: yes

# .......................................................................................
- name: Enable and start pod with systemd
  ansible.builtin.systemd:
    name: "{{ service_properties.name }}"
    state: started
    enabled: yes
