---
# Verify Wazuh deployment

# ....................................................................................
- name: Verify Wazuh pod is running
  become: true
  command: podman pod ps --format {% raw %}"{{.Name}}"{% endraw %}
  register: pod_status
  failed_when: "'wazuh' not in pod_status.stdout"
  changed_when: false

- name: Show pod status
  debug:
    var: pod_status.stdout_lines

# ....................................................................................
- name: Verify Wazuh containers are running
  become: true
  command: podman ps --format {% raw %}"{{.Names}}"{% endraw %} --filter "pod=wazuh"
  register: container_status
  failed_when: >
    'wazuh-indexer' not in container_status.stdout or
    'wazuh-manager' not in container_status.stdout or
    'wazuh-dashboard' not in container_status.stdout
  changed_when: false

- name: Show container status
  debug:
    var: container_status.stdout_lines

# ....................................................................................
# Check Wazuh Indexer
- name: Check Wazuh Indexer health
  uri:
    url: "https://127.0.0.1:{{ wazuh_indexer_port }}/_cluster/health"
    method: GET
    user: admin
    password: "{{ wazuh_admin_password }}"
    force_basic_auth: true
    validate_certs: false
    status_code: 200
  register: indexer_health
  no_log: true

- name: Show indexer health
  debug:
    var: indexer_health.json

# ....................................................................................
# Check Wazuh Manager
- name: Check Wazuh Manager status
  command: >
    podman exec wazuh-manager
    /var/ossec/bin/ossec-control status
  register: manager_status
  changed_when: false

- name: Show manager status
  debug:
    var: manager_status.stdout_lines

# ....................................................................................
# Check Wazuh API
- name: Check Wazuh API status
  uri:
    url: "https://127.0.0.1:{{ wazuh_api_port }}/version"
    method: GET
    user: "{{ wazuh_api_user }}"
    password: "{{ wazuh_api_password }}"
    force_basic_auth: true
    validate_certs: false
    status_code: 200
  register: api_status
  no_log: true

- name: Show API status
  debug:
    var: api_status.json

# ....................................................................................
# Check Dashboard
- name: Check Wazuh Dashboard status
  uri:
    url: "https://127.0.0.1:8080/status"
    method: GET
    validate_certs: false
    status_code: 200
  register: dashboard_status
  ignore_errors: true

- name: Show dashboard status
  debug:
    var: dashboard_status

# ....................................................................................
# Get Wazuh Info
- name: Get Wazuh cluster info
  uri:
    url: "https://127.0.0.1:{{ wazuh_api_port }}/cluster/status"
    method: GET
    user: "{{ wazuh_api_user }}"
    password: "{{ wazuh_api_password }}"
    force_basic_auth: true
    validate_certs: false
    status_code: 200
  register: cluster_info
  no_log: true

- name: Show cluster info
  debug:
    var: cluster_info.json

# ....................................................................................
# Check agent enrollment password
- name: Check agent authorization service
  become: true
  command: >
    podman exec wazuh-manager
    /var/ossec/bin/agent_control -m
  register: auth_status
  changed_when: false

- name: Show auth status
  debug:
    var: auth_status.stdout_lines
