---
- name: Verify
  hosts: "{{ lookup('env', 'MOLECULE_PLATFORM_NAME', default='all') }}"
  become: true
  serial: "{{ lookup('env', 'MOLECULE_SERIAL', default='0') }}"

  vars:
    molecule_nolog: true
    # verify_timestamp set in converge.yml via cacheable fact, fallback provided in tasks
    on_github: "{{ lookup('env', 'IN_GITHUB_CI', default=false) }}"

  tasks:
    #
    # .....................................................................
    #
    - name: Set verify timestamp if not already set from converge
      set_fact:
        verify_timestamp: "{{ ansible_facts['date_time']['iso8601'] }}"
      when: verify_timestamp is not defined

    - name: Ensure verify_output directory exists
      ansible.builtin.file:
        path: "{{ report_root }}"
        state: directory
        mode: "0755"
      delegate_to: localhost
      become: false

    # .....................................................................
    - name: Debug information
      debug:
        msg:
          - "GithubCi: {{ on_github }}"
          - "Playbook dir: {{ playbook_dir }}"
          - "Roles path: {{ playbook_dir }}/../../roles"
          - "Project_root: {{ project_root }}"
          - "Distribution: {{ ansible_facts['distribution'] }}"
          - "Testing services: {{ testing_services }}"

    # ................................................................
    # note this has to be loaded in each phase playbook!
    # This sets container_services variable
    - name: Load service role definitions
      include_vars:
        file: "{{ project_root }}/molecule/vars/services.yml"

    # ................................................................
    - name: Get listening ports for selected services
      set_fact:
        container_service_ports: >-
          {{
            testing_services |
            map('extract', container_services) |
            map(attribute='service_ports') |
            flatten |
            list
          }}

    # ................................................................
    - name: Get service names for selected services
      set_fact:
        monitored_services: >-
          {{
            testing_services |
            map('extract', container_services) |
            map(attribute='service_names') |
            flatten |
            list
          }}

    # ................................................................
    - name: Debug service ports
      debug:
        msg:
          - "Testing Services: {{ testing_services }}"
          - "Service Ports: {{ container_service_ports }}"
        verbosity: 0

    # ................................................................
    - name: Initialize result for capability
      set_fact:
        all_verify_results: {}
        all_verify_failed: {}

    # .......................................................................
    - name: Run pre-verify container diagnostics
      ansible.builtin.include_tasks:
        file: "{{ project_root }}/molecule/shared/diagnostics/main.yml"
      vars:
        report_suffix: "preverify"

    # .......................................................................
    # Version 2 - Adapted for container services
    #
    # This is a nested loop that iterates over the testing_services
    # Each service runs its verify tasks from roles/<service>/tasks/verify.yml
    #
    - name: Run service-specific verifications
      loop: "{{ testing_services }}"
      include_tasks: verify-service.yml
      loop_control:
        loop_var: service
        label: "Verifying {{ service }} service"

    # .......................................................................
    - name: Run post-verify container diagnostics
      ansible.builtin.include_tasks:
        file: "{{ project_root }}/molecule/shared/diagnostics/main.yml"
      vars:
        report_suffix: "postverify"

    # .......................................................................
    - name: Report Results
      ansible.builtin.include_tasks:
        file: report.yml

    # .......................................................................
    # TODO: review this.
    - name: Create verification status map
      set_fact:
        verification_status: >-
          {{
            verification_status | default({}) | combine(
              { service: hostvars[inventory_hostname][service + '_verify_failed'] | default(false) }
            )
          }}
      loop: "{{ testing_services }}"
      loop_control:
        loop_var: service

    # .......................................................................
    - name: Final verification check
      fail:
        msg: "Verifications failed: {{ verification_status | dict2items | selectattr('value', 'true') | map(attribute='key') | list | join(', ') }}"
      when: verification_status.values() | list | select('true') | list | length > 0

    # .......................................................................
    - name: Run Gitlab CI only tasks
      when: on_github
      ansible.builtin.include_tasks: "verify-github.yml"
