---
# This task file retrieves MinIO credentials from HashiVault when available
# and falls back to inventory variables or environment variables when not

- name: Check if HashiVault is configured and accessible
  uri:
    url: "http://{{ vault_host | default('localhost') }}:{{ vault_port | default(8200) }}/v1/sys/health"
    method: GET
    status_code: [200, 429, 472, 473, 501, 503] # Include non-healthy status codes
  register: vault_health
  ignore_errors: true
  no_log: true

- name: Set vault_available fact
  set_fact:
    vault_available: "{{ vault_health is success and vault_health.status in [200, 429, 472, 473] }}"

# =========================================================
# Retrieve secrets from HashiVault if available
# =========================================================
- name: Retrieve MinIO credentials from HashiVault
  when: vault_available | bool
  block:
    - name: Get MinIO admin credentials from HashiVault
      uri:
        url: "http://{{ vault_host | default('localhost') }}:{{ vault_port | default(8200) }}/v1/secret/data/minio/admin"
        method: GET
        headers:
          X-Vault-Token: "{{ vault_token }}"
        status_code: 200
      register: admin_creds
      no_log: true

    - name: Set admin credentials from HashiVault
      set_fact:
        minio_root_user: "{{ admin_creds.json.data.data.username }}"
        minio_root_password: "{{ admin_creds.json.data.data.password }}"
      no_log: true
      when: admin_creds is success

    - name: Get MinIO user credentials from HashiVault
      uri:
        url: "http://{{ vault_host | default('localhost') }}:{{ vault_port | default(8200) }}/v1/secret/data/minio/users"
        method: GET
        headers:
          X-Vault-Token: "{{ vault_token }}"
        status_code: 200
      register: user_creds
      no_log: true

    - name: Set user credentials from HashiVault
      set_fact:
        minio_users: "{{ user_creds.json.data.data.users }}"
      no_log: true
      when: user_creds is success

# =========================================================
# Fall back to environment variables or inventory defaults
# =========================================================
- name: Use environment variables or inventory defaults for credentials
  when: not (vault_available | bool)
  block:
    - name: Get credentials from environment variables if available
      set_fact:
        minio_root_user: "{{ lookup('env', 'MINIO_ROOT_USER') | default(minio_root_user) }}"
        minio_root_password: "{{ lookup('env', 'MINIO_ROOT_PASSWORD') | default(minio_root_password) }}"
      no_log: true

    - name: Verify credentials are set
      assert:
        that:
          - minio_root_user is defined and minio_root_user != ''
          - minio_root_password is defined and minio_root_password != ''
        fail_msg: "MinIO credentials not found in HashiVault, environment variables, or inventory"

    - name: Display credential source
      debug:
        msg: "Using MinIO credentials from inventory or environment variables"
