---
- name: Stop and disable services
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: stopped
    enabled: no
    scope: user
  loop:
    - pod-elasticsearch
  ignore_errors: true

- name: Remove pod and containers
  containers.podman.podman_pod:
    name: elasticsearch
    state: absent
  ignore_errors: true

- name: Remove systemd services
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/systemd/user/{{ item }}"
    state: absent
  loop:
    - pod-elasticsearch.service
    - container-elasticsearch-node.service
    - container-elasticsearch-gui.service

- name: Remove Quadlet files
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/containers/systemd/{{ item }}"
    state: absent
  loop:
    - elasticsearch.pod
    - elasticsearch-node.container
    - elasticsearch-gui.container

- name: Reload systemd user daemon
  ansible.builtin.systemd:
    daemon_reload: yes
    scope: user

- name: Remove data directory
  ansible.builtin.file:
    path: "{{ elasticsearch_data_dir }}"
    state: absent
  when: elasticsearch_delete_data | bool