---
#
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#
- name: Set service name based on deployment type
  set_fact:
    elasticsearch_service_name: "pod-elasticsearch"
    elasticsearch_pod_key: "elasticsearch.pod"
  when: not elasticsearch_use_quadlet | bool

# .................................................................
- name: Stop and disable services
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: stopped
    enabled: no
    scope: user
  loop:
    - "{{ elasticsearch_service_name }}"
  ignore_errors: true

# .................................................................
# These are only present when generated
#
- name: Remove systemd services
  when: not elasticsearch_use_quadlet | bool
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/systemd/user/{{ item }}"
    state: absent
  loop:
    - pod-elasticsearch.service
    - container-elasticsearch-node.service
    - container-elasticsearch-gui.service

# .................................................................
- name: Remove Quadlet files
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/containers/systemd/{{ item }}"
    state: absent
  loop:
    - elasticsearch.pod
    - elasticsearch-node.container
    - elasticsearch-gui.container

# .................................................................
- name: reload systemd user daemon
  ansible.builtin.systemd:
    daemon_reload: yes
    scope: user

# .................................................................
- name: Remove all traces
  when: elasticsearch_state == 'absent' and elasticsearch_purge | default(false)
  block:
    - name: Remove configuration
      file:
        path: "{{ elasticsearch_data_dir }}"
        state: absent
    - name: Remove systemd files
      file:
        path: "{{ item }}"
        state: absent
      with_fileglob:
        - "~/.config/systemd/user/*elasticsearch*"
