---
#
# SMELL
#   I have hard coded the data_dir in the role defaults, but
#   I know that a the services data directory are in the default
#   Having multiple places to set a var seems poor.
#
#   the elasticsarch_data_dir is set in  defaults/main.yml and
#   the test playbooks.  I will likly need to reasses how to use
#   the service_properties dictionary. I am not so happy with this
#   type of syntax.
#
#   service_properties: "{{ service_properties | combine({'state': 'absent'}) }}"
#
#
# ............................................................
- name: Verify prerequisites
  assert:
    that:
      - elasticsearch_data_dir is defined
    fail_msg: "Required variables not properly configured"

# ............................................................
- name: Base prepare
  ansible.builtin.include_tasks:
    file: ../_base/tasks/prepare.yml
