---
- name: Create Elasticsearch directories
  ansible.builtin.file:
    path: "{{ elasticsearch_data_dir }}/{{ item }}"
    state: directory
    mode: "0750"
  loop:
    - "" # Creates the base directory
    - config
    - data
    - logs

- name: Template elasticsearch.yml config
  ansible.builtin.template:
    src: elasticsearch.yml.j2
    dest: "{{ elasticsearch_data_dir }}/config/elasticsearch.yml"
    mode: "0644"
  notify: restart elasticsearch