---
#
# .......................................................................................
- name: Ensure required directories exist
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/{{ item }}"
    state: directory
    mode: "0750"
  loop:
    - .config/systemd/user
    - .config/containers/systemd

# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
- name: Set service name based on deployment type
  set_fact:
    elasticsearch_service_name: "pod-elasticsearch"
    elasticsearch_pod_key: "elasticsearch"
  when: not elasticsearch_use_quadlet | bool

# .......................................................................................
- name: Template System configuration files for either quadlet and systemd
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ ansible_env.HOME }}/.config/containers/systemd/{{ item.dest }}"
    mode: "0644"
  loop:
    - { src: elasticsearch.pod.j2, dest: elasticsearch.pod }
    - {
        src: elasticsearch-node.container.j2,
        dest: elasticsearch-node.container,
      }
    - { src: elasticsearch-gui.container.j2, dest: elasticsearch-gui.container }

# .......................................................................................
# Generator  add pod- or container-  to --name  by default
# Older podman versions may have issues
#
- name: Generate systemd units from Quadlets
  when: not elasticsearch_use_quadlet | bool
  ansible.builtin.command:
    cmd: podman generate systemd --name elasticsearch --files --new
    chdir: "{{ ansible_env.HOME }}/.config/systemd/user"
  register: generate_result
  changed_when: generate_result.rc == 0

# .......................................................................................
- name: Reload systemd user daemon
  ansible.builtin.systemd:
    daemon_reload: yes
    scope: user

# .......................................................................................
- name: Enable and start pod with systemd
  ansible.builtin.systemd:
    name: "{{ elasticsearch_service_name }}"
    state: started
    enabled: yes
    scope: user
