---
- name: Stop and disable services
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: stopped
    enabled: no
    scope: user
  loop:
    - pod-traefik
  ignore_errors: true

- name: Remove pod and containers
  containers.podman.podman_pod:
    name: traefik
    state: absent
  ignore_errors: true

- name: Remove systemd services
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/systemd/user/{{ item }}"
    state: absent
  loop:
    - pod-traefik.service
    - container-traefik-svc.service

- name: Remove Quadlet files
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/containers/systemd/{{ item }}"
    state: absent
  loop:
    - traefik.pod
    - traefik-svc.container

- name: Remove data directory
  ansible.builtin.file:
    path: "{{ traefik_data_dir }}"
    state: absent
  when: traefik_delete_data | bool

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes
    scope: user
