---
#
#  does both privilege and rootless.
#  I am holding on hope rootless can happen
#
#
# ...........................................................
- name: Stop and disable rootless service
  when: not traefik_privileged
  ansible.builtin.systemd:
    name: traefik-pod
    state: stopped
    enabled: no
    scope: user
  ignore_errors: true

- name: Stop and disable privileged service
  when: traefik_privileged
  become: true
  ansible.builtin.systemd:
    name: pod-traefik
    state: stopped
    enabled: no
  ignore_errors: true

# ...........................................................
# We have to remove this to disable I think... TODO:  test this.
- name: Remove rootless Quadlet files
  when: not traefik_privileged
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/containers/systemd/{{ item }}"
    state: absent
  loop:
    - traefik.pod
    - traefik-svc.container

- name: Remove privileged Quadlet files
  when: traefik_privileged
  become: true
  ansible.builtin.file:
    path: "/etc/containers/systemd/{{ item }}"
    state: absent
  loop:
    - traefik.pod
    - traefik-svc.container

# ...........................................................
# This is the magic that make a quadlet runnable via systemd
- name: Reload user systemd
  when: not traefik_privileged
  ansible.builtin.systemd:
    daemon_reload: yes
    scope: user

- name: Reload system systemd
  when: traefik_privileged
  become: true
  ansible.builtin.systemd:
    daemon_reload: yes

# ...........................................................
# Claude...I need a way to short circuit two things
# 1. check that you can become: true early
# 2. fix the playbooks to exit early
#
- name: Remove data directory
  become: true
  ansible.builtin.file:
    path: "{{ traefik_data_dir }}"
    state: absent
  when: traefik_delete_data | bool
