---
#
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
#
- name: Set service name based on deployment type
  set_fact:
    vault_service_name: "pod-vault"
    vault_pod_key: "vault"
  when: not vault_use_quadlet | bool

# .................................................................
- name: Stop and disable services
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: stopped
    enabled: no
    scope: user
  loop:
    - "{{ vault_service_name }}"
  ignore_errors: true

# .................................................................
# These are only present when generated
#
- name: Remove systemd services
  when: not vault_use_quadlet | bool
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/systemd/user/{{ item }}"
    state: absent
  loop:
    - pod-vault.service
    - container-vault-svc.service

# .................................................................
- name: Remove Quadlet files
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/containers/systemd/{{ item }}"
    state: absent
  loop:
    - vault.pod
    - vault-svc.container

# .................................................................
- name: reload systemd user daemon
  ansible.builtin.systemd:
    daemon_reload: yes
    scope: user

# .................................................................
- name: Remove all traces
  when: vault_state == 'absent' and vault_purge | default(false)
  block:
    - name: Remove configuration
      file:
        path: "{{ vault_data_dir }}"
        state: absent
    - name: Remove systemd files
      file:
        path: "{{ item }}"
        state: absent
      with_fileglob:
        - "~/.config/systemd/user/*vault*"
