---
- name: Create Vault pod
  containers.podman.podman_pod:
    name: vault
    ports:
      - "127.0.0.1:{{ vault_api_port }}:8200"
      - "127.0.0.1:{{ vault_cluster_port }}:8201"

- name: Deploy Vault container
  containers.podman.podman_container:
    name: vault-svc
    pod: vault
    image: "{{ vault_image }}"
    state: started
    command: "server"
    volume:
      - "{{ vault_data_dir }}/config:/vault/config:Z"
      - "{{ vault_data_dir }}/data:/vault/data:Z"
      - "{{ vault_data_dir }}/logs:/vault/logs:Z"
      - "{{ vault_data_dir }}/tls:/vault/tls:Z"
    env:
      VAULT_ADDR: "http://127.0.0.1:8200"
      VAULT_API_ADDR: "http://127.0.0.1:8200"
      VAULT_CLUSTER_ADDR: "http://127.0.0.1:8201"
    cap_add:
      - IPC_LOCK
    restart_policy: always

- name: Verify container status
  command: podman ps --format {% raw %}"{{.Names}}"{% endraw %} --filter "pod=vault"
  register: container_status
  changed_when: false
