---
- name: Install Vault
  when: vault_state == 'present'
  block:
    - name: Include prerequisites tasks
      ansible.builtin.include_tasks: prerequisites.yml

    - name: Include TLS tasks
      ansible.builtin.include_tasks: tls.yml
      when: vault_enable_tls | bool

    - name: Include container tasks
      ansible.builtin.include_tasks: quadlet_rootless.yml

    # TODO  build quad_privileged

- name: Remove Vault
  when: vault_state == 'absent'
  block:
    #
    - name: Set the redis service state to absent
      set_fact:
        service_properties: "{{ service_properties | combine({'state': 'absent'}) }}"

    # ...............................................................................
    - name: Include cleanup tasks
      ansible.builtin.include_tasks:
        file: "../_base/tasks/cleanup.yml"
      vars:
        service_delete_data: "{{ vault_delete_data }}"
