---
#
# .......................................................................................
- name: Ensure required directories exist
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/{{ item }}"
    state: directory
    mode: "0750"
  loop:
    - .config/systemd/user
    - .config/containers/systemd

# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
- name: Set service name based on deployment type
  set_fact:
    vault_service_name: "pod-vault"
    vault_pod_key: "vault"
  when: not vault_use_quadlet | bool

# .......................................................................................
- name: Template System configuration files for either quadlet and systemd
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ ansible_env.HOME }}/.config/containers/systemd/{{ item.dest }}"
    mode: "0644"
  loop:
    - { src: vault.pod.j2, dest: vault.pod }
    - { src: vault-svc.container.j2, dest: vault-svc.container }

# .......................................................................................
- name: Generate systemd units
  when: not vault_use_quadlet | bool
  command:
    cmd: podman generate systemd --name vault --files --new
    chdir: "{{ ansible_env.HOME }}/.config/systemd/user"
  register: generate_result
  changed_when: generate_result.rc == 0

# .......................................................................................
- name: Reload systemd user daemon
  ansible.builtin.systemd:
    daemon_reload: yes
    scope: user

# .......................................................................................
- name: Enable and start services
  systemd:
    name: "{{ vault_service_name }}"
    state: started
    enabled: yes
    scope: user
