---
#
# .......................................................................................
- name: Ensure required directories exist
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/{{ item }}"
    state: directory
    mode: "0750"
  loop:
    - .config/systemd/user
    - .config/containers/systemd

# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
- name: Set service name based on deployment type
  set_fact:
    vault_service_name: "pod-vault"
    vault_pod_key: "vault"
  when: not vault_use_quadlet | bool

# .......................................................................................
- name: reload systemd user daemon
  ansible.builtin.systemd:
    daemon_reload: yes
    scope: user

# .......................................................................................
- name: Enable and start services
  systemd:
    name: "{{ vault_service_name }}"
    state: started
    enabled: yes
    scope: user
