# deploy-elasticsearch.yml
---
- name: Deploy Elasticsearch
  hosts: elasticsearch_svc
  vars:
    elasticsearch_password: "{{ lookup('env', 'ELASTIC_PASSWORD', default='') }}"

  roles:
    - role: elasticsearch
      vars:
        elasticsearch_memory: "1g"
