# deploy-elasticsearch.yml
---
- name: Deploy Elasticsearch
  hosts: elasticsearch_svc
  vars:
    mattermost_state: present
    elasticsearch_password: "{{ lookup('env', 'ELASTIC_PASSWORD', default='') }}"
  roles:
    - role: elasticsearch
