---
- name: Deploy Traefik
  hosts: traefik_svc
  vars:
    traefik_force_reload: false

  pre_tasks:
    - name: I am here
      ansible.builtin.debug:
        var: traefik_force_reload
  roles:
    - role: traefik
  post_tasks:
    - name: I was here
      ansible.builtin.debug:
        var: traefik_force_reload
