---
#
# prepare-elasticsearch.yml - Run with ansible-playbook -K prepare-elasticsearch.yml
#
- name: Prepare system for container deployments
  hosts: elasticsearch_svc
  vars:
    # SMELL should this come in via inventory
    elasticsearch_data_dir: "{{ ansible_env.HOME }}/elasticsearch-data" #
    elasticsearch_state: prepare
  roles:
    - role: elasticsearch
