---
- name: Prepare system for traefik installation
  hosts: traefik_svc
  # SMELL should this come in via inventory
  vars:
    traefik_data_dir: "{{ ansible_env.HOME }}/traefik-data"
    traefik_state: prepare
  roles:
    - role: traefik
