#
# prepare-hashivault.yml - Run with ansible-playbook -K prepare-hashivault.yml
#
---
- name: Prepare system for HashiVault deployment
  hosts: hashivault_svc
  vars:
    vault_data_dir: "{{ ansible_env.HOME }}/vault-data"

  tasks:
    - name: Prepare Hashivault
      ansible.builtin.include_role:
        name: hashivault
        tasks_from: prepare
        defaults_from: main
