- name: Prepare system for Redis installation
  hosts: redis_svc
  vars:
    redis_data_dir: "{{ ansible_env.HOME }}/redis-data"

  tasks:
    #
    # ==========================================================
    # These tasks run as the regular user

    - name: Create Redis directory structure
      ansible.builtin.file:
        path: "{{ redis_data_dir }}/{{ item.path }}"
        state: directory
        mode: "{{ item.mode }}"
        # owner: "{{ ansible_user_id }}"
        # group: "{{ ansible_user_id }}"
      loop:
        - { path: "", mode: "0750" }
        - { path: "config", mode: "0755" }
        - { path: "data", mode: "0750" }

    # ==========================================================
    # These tasks require root

    # ...........................................................
    - name: Perform system-level tasks
      become: true
      block:
        #
        # ...........................................................
        - name: Set SELinux context for Mattermost directories
          ansible.builtin.command: chcon -Rt container_file_t {{ redis_data_dir }}
          become: true
          when: ansible_os_family == "RedHat"

        # ...........................................................
        # RHEL/CentOS specific tasks
        - name: Configure RHEL repositories
          block:
            - name: Enable CRB repository
              rhsm_repository:
                name: codeready-builder-for-rhel-9-x86_64-rpms
                state: enabled
              when: ansible_distribution_major_version == "9"
          when: ansible_os_family == "RedHat"

        # ...........................................................
        # Debian/Ubuntu specific tasks
        - name: Configure Debian prerequisites
          block:
            - name: Install required dependencies
              apt:
                name:
                  - apt-transport-https
                  - ca-certificates
                  - curl
                  - gnupg
                  - python3-pip
                state: present
                update_cache: yes

            - name: Install podman-compose via pip
              pip:
                name: podman-compose
                state: present
          when: ansible_os_family == "Debian"

        # .................................................................
        # Common tasks for all distributions
        - name: Install required packages
          package:
            name: "{{ packages }}"
            state: present
          vars:
            packages:
              - podman
              - "{{ 'podman-compose' if ansible_os_family == 'RedHat' else '' }}"
          register: package_result
          until: package_result is success
          retries: 3
          delay: 5

        # .................................................................
        - name: Enable lingering for user
          command: "loginctl enable-linger {{ ansible_user_id }}"
          changed_when: false

        # .................................................................
        - name: Configure container DNS
          block:
            - name: Create containers configuration directory
              file:
                path: "{{ ansible_env.HOME }}/.config/containers"
                state: directory
                mode: "0755"

            - name: Configure DNS in containers.conf
              copy:
                dest: "{{ ansible_env.HOME }}/.config/containers/containers.conf"
                content: |
                  [containers]
                  dns_servers = ["1.1.1.1", "8.8.8.8"]
                mode: "0644"

        # .................................................................
        - name: Configure SELinux
          block:
            - name: Set container file context
              sefcontext:
                target: "{{ redis_data_dir }}(/.*)?"
                setype: container_file_t
                state: present

            - name: Apply SELinux context
              command: restorecon -Rv "{{ redis_data_dir }}"
          when: ansible_os_family == "RedHat"
