---
- name: Prepare system for traefik installation
  hosts: traefik_svc
  # SMELL should this come in via inventory
  vars:
    traefik_data_dir: "{{ ansible_env.HOME }}/traefik-data"

  tasks:
    - name: Prepare traefik
      ansible.builtin.include_role:
        name: traefik
        tasks_from: prepare
        defaults_from: main
