- name: Prepare system for Redis installation
  hosts: redis_svc
  vars:
    redis_data_dir: "{{ ansible_env.HOME }}/redis-data"

  tasks:
    #
    # These tasks run as the regular user
    #
    - name: Create Redis directory structure
      ansible.builtin.file:
        path: "{{ redis_data_dir }}/{{ item.path }}"
        state: directory
        mode: "{{ item.mode }}"
        # owner: "{{ ansible_user_id }}"
        # group: "{{ ansible_user_id }}"
      loop:
        - { path: "", mode: "0750" }
        - { path: "config", mode: "0755" }
        - { path: "data", mode: "0750" }

    # These tasks need root
    #
    - name: Perform system-level tasks
      become: true
      block:
        # Configure SELinux for RHEL/CentOS
        - name: Configure SELinux
          block:
            - name: Set container file context
              sefcontext:
                target: "{{ redis_data_dir }}(/.*)?"
                setype: container_file_t
                state: present

            - name: Apply SELinux context
              command: restorecon -Rv "{{ redis_data_dir }}"
          when: ansible_os_family == "RedHat"
