---
#
# prepare-mattermost.yml - Run with ansible-playbook -K prepare-mattermost.yml
#
- name: Prepare system for Mattermost installation
  hosts: mattermost_svc
  vars:
    mattermost_data_dir: "{{ ansible_env.HOME }}/mattermost-data" # Use HOME instead of user_dir

  tasks:
    # These tasks run as the regular user
    - name: Create Mattermost directories
      file:
        path: "{{ mattermost_data_dir }}/{{ item }}"
        state: directory
        mode: "0750"
      loop:
        - "" # Creates the base directory
        - config
        - data
        - logs
        - plugins
        - client/plugins

    - name: Create PostgreSQL data directory with special permissions
      file:
        path: "{{ mattermost_data_dir }}/postgres"
        state: directory
        mode: "0700"

    # These tasks need root
    - name: Perform system-level tasks
      become: true
      block:
        - name: Install required packages
          package:
            name:
              - podman
              - podman-compose
            state: present

        - name: Enable lingering for user
          command: "loginctl enable-linger {{ ansible_user_id }}"
          changed_when: false

        - name: Set SELinux context for container volumes
          block:
            - name: Set container file context
              sefcontext:
                target: "{{ mattermost_data_dir }}(/.*)?"
                setype: container_file_t
                state: present

            - name: Apply SELinux context
              command: restorecon -Rv "{{ mattermost_data_dir }}"
          when: ansible_os_family == "RedHat"
