---
- name: Prepare system for Redis installation
  hosts: redis_svc
  # SMELL should this come in via inventory
  vars:
    redis_data_dir: "{{ ansible_env.HOME }}/redis-data"

  tasks:
    - name: Prepare Redis
      ansible.builtin.include_role:
        name: redis
        tasks_from: prepare
        defaults_from: main
