---
#
# prepare-elasticsearch.yml - Run with ansible-playbook -K prepare-elasticsearch.yml
#
- name: Prepare system for container deployments
  hosts: elasticsearch_svc
  vars:
    # SMELL should this come in via inventory
    elasticsearch_data_dir: "{{ ansible_env.HOME }}/elasticsearch-data" #

  tasks:
    - name: Prepare Elasticsearch
      ansible.builtin.include_role:
        name: elasticsearch
        tasks_from: prepare
        defaults_from: main
