---
#
# prepare-matterost.yml - Run with ansible-playbook -K prepare-mattermost.yml
#
- name: Prepare system for Mattermost installation
  hosts: mattermost_svc
  vars:
    mattermost_data_dir: "{{ ansible_env.HOME }}/mattermost-data"

  tasks:
    - name: Prepare Mattermost
      ansible.builtin.include_role:
        name: mattermost
        tasks_from: prepare
        defaults_from: main
