#
# prepare-hashivault.yml - Run with ansible-playbook -K prepare-hashivault.yml
#
---
- name: Prepare system for HashiVault deployment
  hosts: hashivault_svc
  vars:
    vault_data_dir: "{{ ansible_env.HOME }}/vault-data"
    vault_state: prepare
  roles:
    - role: hashivault
