#
# prepare-traefik.yml - Run with ansible-playbook -K prepare-traefik.yml
#
---
- name: Prepare system for Traefik deployment
  hosts: traefik_svc
  vars:
    traefik_data_dir: "{{ ansible_env.HOME }}/traefik-data"

  tasks:
    #
    # These tasks run as the regular user
    # ...........................................................................
    - name: Create Traefik directories
      file:
        path: "{{ traefik_data_dir }}/{{ item }}"
        state: directory
        mode: "0750"
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
      loop:
        - "" # Creates base directory
        - config
        - acme
        - logs

    # ...........................................................................
    - name: Perform system-level tasks
      become: true
      block:
        #
        - name: Set proper SELinux context for Elasticsearch directories
          ansible.builtin.command:
            cmd: "chcon -Rt container_file_t {{ traefik_data_dir }}"
          changed_when: false
          when: ansible_selinux.status == "enabled"

        # RHEL/CentOS specific tasks
        - name: Configure RHEL repositories
          when: ansible_os_family == "RedHat"
          block:
            - name: Enable CRB repository
              rhsm_repository:
                name: codeready-builder-for-rhel-9-x86_64-rpms
                state: enabled
              when: ansible_distribution_major_version == "9"

        # Debian/Ubuntu specific tasks
        - name: Configure Debian prerequisites
          when: ansible_os_family == "Debian"
          block:
            - name: Install required dependencies
              apt:
                name:
                  - apt-transport-https
                  - ca-certificates
                  - curl
                  - gnupg
                  - python3-pip
                state: present
                update_cache: yes

            - name: Install podman-compose via pip
              pip:
                name: podman-compose
                state: present

        # Common tasks for all distributions
        - name: Install required packages
          package:
            name: "{{ packages }}"
            state: present
          vars:
            packages:
              - podman
              - "{{ 'podman-compose' if ansible_os_family == 'RedHat' else '' }}"
          register: package_result
          until: package_result is success
          retries: 3
          delay: 5

        - name: Enable lingering for user
          command: "loginctl enable-linger {{ ansible_user_id }}"
          changed_when: false

        # SELinux configuration (when on RHEL/CentOS)
        - name: Configure SELinux
          block:
            - name: Install SELinux policy tools
              package:
                name:
                  - policycoreutils-python-utils
                state: present

            - name: Set SELinux context for Traefik directories
              sefcontext:
                target: "{{ traefik_data_dir }}(/.*)?"
                setype: container_file_t
                state: present

            - name: Apply SELinux context
              command: restorecon -Rv "{{ traefik_data_dir }}"
              register: restorecon_result
              changed_when: restorecon_result.rc == 0
          when:
            - ansible_os_family == "RedHat"
            - ansible_selinux.status is defined
            - ansible_selinux.status == "enabled"
