---
- name: Verify Mattermost deployment
  hosts: mattermost_svc
  vars:
    test_email: "test-{{ ansible_date_time.epoch }}@example.com"
    test_username: "testuser-{{ ansible_date_time.epoch }}"
    test_password: "Test123!"

  tasks:
    # ....................................................................................
    - name: Include roles vars
      ansible.builtin.include_role:
        name: mattermost
        tasks_from: verify
        vars_from: mattermost
