---
- name: Verify Redis Installation
  hosts: redis_svc
  vars:
    test_key: "test:ansible"
    test_value: "Verification {{ ansible_date_time.iso8601 }}"

  tasks:
    # ....................................................................................
    - name: Include roles vars
      ansible.builtin.include_role:
        name: redis
        tasks_from: verify
        vars_from: redis
