---
- name: Verify Elasticsearch Installation
  hosts: elasticsearch_svc
  vars:
    test_index: "test-ansible"
    test_doc: '{"message": "Verification {{ ansible_date_time.iso8601 }}"}'

  tasks:
    # ....................................................................................
    - name: Include roles vars
      ansible.builtin.include_role:
        name: elasticsearch
        tasks_from: verify
        vars_from: main
