# wazuh/meta/main.yml
---
galaxy_info:
  role_name: wazuh
  namespace: jackaltx
  author: jackaltx
  description: Deploy Wazuh with Podman containers
  license: MIT
  min_ansible_version: "2.9"

  platforms:
    - name: EL
      versions:
        - "9"
    - name: Debian
      versions:
        - bookworm
    - name: Ubuntu
      versions:
        - jammy

  galaxy_tags:
    - wazuh
    - security
    - monitoring
    - siem
    - compliance
    - podman
    - containers

dependencies: []
