name: Lint and Syntax Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  yaml-lint:
    name: YAML Lint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install yamllint
      run: pip install yamllint

    - name: Run yamllint
      run: yamllint .

  markdown-lint:
    name: Markdown Syntax Check
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install markdownlint-cli
      run: npm install -g markdownlint-cli

    - name: Run markdownlint
      run: markdownlint "**/*.md" --ignore node_modules

  ansible-syntax:
    name: Ansible Syntax Check
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Ansible
      run: pip install ansible

    - name: Run Ansible syntax check
      run: |
        find roles -name "*.yml" -type f -exec ansible-playbook --syntax-check {} \;